
from django.urls import path,include
from summary.views import *
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [

    path('totalunassignedlauleads/',TotalUnassignedLAUleads.as_view()),
    path('totallauconsentagents/',LauConsentAgents.as_view()),
    path('lauassiginleadsconsent/',LauAssiginLeadsToConsent.as_view()),
    path('districtlisting/',DistrictListing.as_view()),
    path('aclisting/',ACListing.as_view()),
    path('blocklisting/',BlockListing.as_view()),
    path('gplisting/',GPListing.as_view()),
    path('municipalitylisting/',MunicipalityListing.as_view()),
    path('wardlisting/',WardListing.as_view()),
    path('villagelisting/',VillageListing.as_view()),
    path('castelisting/',CasteListing.as_view()),
    path('categorylisting/',CategoryListing.as_view()),
    path('occupationlisting/',OccupationListing.as_view()),
    path('religionlisting/',ReligionListing.as_view()),
    path('genderlisting/',GenderListing.as_view()),
    path('datasourcelisting/',DataSourceListing.as_view()),
    path('whatsappleadslisting/',WALeadListing.as_view()),
    path('whatsappleadsdistributionBySuperAdmin/',WALeadDistributionBySuperAdmin.as_view()),
    path('rtoleadslisting/',RTOLeadListing.as_view()),
    path('rtoleadsdistributionBySuperAdmin/',RTOLeadDistributionBySuperAdmin.as_view()),
    path('inauguratedleadslisting/',InauguratedLeadListing.as_view()),
    path('lautotalwaagents/',LauTotalWaAgents.as_view()),
    path('lautotalconsentleads/',TotalAluConsentleads.as_view()),
    path('lauadminassignconsenttowaagents/',LauAdminAssiginConsentToWaAgent.as_view()),
    path('uploadingnewleads/',UploadingNewLeads.as_view()),
    path('newleadslisting/',NewLeadsListing.as_view()),
    path('newleaddistributionbysuperadmin/',NewLeadDistributionBySuperAdmin.as_view()),
    path('lauwacompletedleads/',LauWaCompletedLeads.as_view()),
    path('lauwaleadsassignsuperadmin/',LauWALeadAssignToSuperAdmin.as_view()),
    path('assignedleadsforlauagent/',AssignedLeadsForLauAgent.as_view()),
    path('showleadbasicinfotolauagent/',ShowLeadBasicInfoToLauAgent.as_view()),
    path('savechangesbasicinfobylauagent/',SaveChangesBasicInfoByLauAgent.as_view()),
    path('updatewainfobylauagent/',UpdateWaInfoByLauAgent.as_view()),
    # path('updatecrminfobylauagent/',UpdateCRMInfoByLauAgent.as_view()),
    path('laucallstatus/', LauCallStatus.as_view()),
    path('lauleadstatus/', LauLeadStatus.as_view()),
    path('laudistrictwiseinfo/', LauDistrictWiseTableInfo.as_view()),
    path('lauadminsourcewisegraph/', LauAdminSourceWiseGraph.as_view()),
    path('lauadmindistrictwiseconsentgraph/', LauAdminDistrictWiseConsentGraph.as_view()),
    path('lauadmindistrictwisewagraph/', LauAdminDistrictWiseWAGraph.as_view()),
    path('lauadmintilswisedata/', LauAdminTilsWiseData.as_view()),
    path('callingmastersheetdownload/', CallingMasterSheetDownload.as_view()),
]